Repository almondyoung/test2, pull requests merged in 2023-09, with the labels that each got.

#1 [NEW][astral][0.0.1]add astral
  astral/.helmignore
  astral/Chart.yaml
  astral/app.cfg
  astral/templates/NOTES.txt
  astral/templates/_helpers.tpl
  astral/templates/deployment.yaml
  astral/values.yaml
Labels: waiting to review

#2 [NEW][bazarr][0.1.2]add baszrr
  bazarr/.helmignore
  bazarr/Chart.yaml
  bazarr/app.cfg
  bazarr/bazarr.png
  bazarr/templates/NOTES.txt
  bazarr/templates/_helpers.tpl
  bazarr/templates/deployment.yaml
  bazarr/values.yaml
Labels: waiting to review, NEW

#3 [NEW][astral][0.0.1]test add astral2
  astral/.helmignore
  astral/Chart.yaml
  astral/app.cfg
  astral/templates/NOTES.txt
  astral/templates/_helpers.tpl
  astral/templates/deployment.yaml
  astral/values.yaml
Labels: waiting to review, NEW

#4 [NEW][bazarr][0.1.2]add baszrr
  bazarr/.helmignore
  bazarr/Chart.yaml
  bazarr/app.cfg
  bazarr/bazarr.png
  bazarr/templates/NOTES.txt
  bazarr/templates/_helpers.tpl
  bazarr/templates/deployment.yaml
  bazarr/values.yaml
Labels: waiting to review, NEW

#5 [NEW][astral][0.0.1]add astral111
  astral/.helmignore
  astral/Chart.yaml
  astral/app.cfg
  astral/templates/NOTES.txt
  astral/templates/_helpers.tpl
  astral/templates/deployment.yaml
  astral/values.yaml
Labels: waiting to review, NEW

#6 [NEW][bazarr][0.1.2]add baszrr
  bazarr/.helmignore
  bazarr/Chart.yaml
  bazarr/app.cfg
  bazarr/bazarr.png
  bazarr/templates/NOTES.txt
  bazarr/templates/_helpers.tpl
  bazarr/templates/deployment.yaml
  bazarr/values.yaml
Labels: waiting to review, NEW

#9 [NEW][astral][0.0.4]test1
  astral/.helmignore
  astral/Chart.yaml
  astral/app.cfg
  astral/templates/NOTES.txt
  astral/templates/_helpers.tpl
  astral/templates/deployment.yaml
  astral/values.yaml
Labels: waiting to review, NEW

#14 [NEW][calibre][0.0.1]add calibre
  calibre/.helmignore
  calibre/Chart.yaml
  calibre/app.cfg
  calibre/calibre.png
  calibre/templates/NOTES.txt
  calibre/templates/_helpers.tpl
  calibre/templates/deployment.yaml
  calibre/values.yaml
Labels: waiting to review, NEW

#17 [UPDATE][calibre][0.0.2]test2
  calibre/Chart.yaml
  calibre/app.cfg
Labels: waiting to review, UPDATE

#18 [SUSPEND][calibre][0.0.2]test2
  calibre/.suspend
Labels: waiting to review, SUSPEND

#19 [REMOVE][calibre][0.0.2]test2
  calibre/.remove
Labels: waiting to review, REMOVE

#20 [UPDATE][calibre][0.0.2]test2
  calibre/.remove
  calibre/.suspend
  calibre/Chart.yaml
Labels: waiting to review, UPDATE

#21 [UPDATE][calibre][0.0.2]test
  calibre/Chart.yaml
Labels: waiting to review, UPDATE

#23 [NEW][openllm][0.0.6] test
  openllm/Chart.yaml
  openllm/app.cfg
  openllm/templates/deployment.yaml
  openllm/templates/traefik.yaml
  openllm/values.yaml
Labels: waiting to review, NEW
